name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Read Swagger Specification
      run: |
        dotnet run --project IonPropeller
        curl -fsSL http://localhost:7244/swagger/v1/swagger.json -o swagger.json
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: swagger.json
        path: swagger.json
